version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/arm64 
volumes:
  postgres_data: